services:
  - type: web
    name: ai-interview-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.8
      - key: RENDER_PYTHON_VERSION
        value: 3.12.8
      - key: MONGODB_URL
        sync: false
      - key: HF_API_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: HF_MODEL_URL
        value: https://router.huggingface.co/v1/chat/completions